version: "2"

plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby: {}
        javascript:
          mass_threshold: 40
    exclude_paths:
      - "client/**/__tests__/"
  eslint:
    enabled: true
    channel: "stable"
    exclude_paths:
      - public/javascripts/
      - vendor/assets/javascripts/
      - client/flow/
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: "stable"
ratings:
  paths:
    - "**.rb"
    - "**.erb"
    - "**.css"
    - "**.js"
engines:
  duplication:
    enabled: true
  rubocop:
    enabled: true
  csslint:
    enabled: true
exclude_paths:
  - config/
  - db/
  - spec/