---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    exclude_paths:
    - public/javascripts/
  fixme:
    enabled: true
  rubocop:
    enabled: true
    exclude_fingerprints:
    - af17961d1a142550788e9465cdce8388
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.rb"
  - "**.css"
  - "**.js"
exclude_paths:
- config/
- db/
- spec/
