AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'client/node_modules/**/*'

Documentation:
  Enabled: false

Rails:
  Enabled: true

# There is a bug in the Rubocop 0.48 parser that causes it to incorrectly
# complain about parentheses around blocks used with scopes. This should be
# removed once it is possible to upgrade to 0.49 or above.
Lint/AmbiguousBlockAssociation:
  Enabled: false

# Rubocop should be used for style guide adherence, not testing for code smell
Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
