FROM ruby:2.6-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential cmake git tzdata libpq-dev  ruby-dev curl

# Install nodejs
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash - && \
  apt-get install -y nodejs

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /app
WORKDIR /app

# ADD Gemfile /app/Gemfile
# ADD Gemfile.lock /app/Gemfile.lock
RUN gem install bundler -v 2.0.1
# RUN bundle install --retry=5 --deployment --without github production staging
#
#ENV BUNDLE_PATH=/bundle \
#    BUNDLE_BIN=/bundle/bin \
 #    GEM_HOME=/bundle

# COPY . /app
CMD ["bash"]
