AllCops:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - "googleauth.gemspec"
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Enabled: false
Style/IndentHeredoc:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/PercentLiteralDelimiters: # Contradicting rule
  Enabled: false
Style/SymbolArray: # Undefined syntax in Ruby 1.9.3
  Enabled: false

