development:
  google_client_id: no-id
  google_client_secret: no-secret

test:
  google_client_id: no-id
  google_client_secret: no-secret

# production:
#   google_client_id: ...
#   google_client_secret: ...
