default: &default
  adapter: postgresql
  allow_concurrency: true
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  host: <%= ENV['PSQL_HOST'] || 'localhost' %>
  database: ifme_development
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
  min_messages: warning
test:
  <<: *default
  database: ifme_test
  min_messages: error
production:
  <<: *default
  database: ifme_production
  username: <%= ENV['PSQL_USERNAME'] %>
  password: <%= ENV['PSQL_PASSWORD'] %>
