files: ["**/*.js"] # No need to put app/assets/ or vendor/assets here
exclude_paths: []
options:
  boss:       true
  browser:    true
  curly:      true
  eqeqeq:     true
  eqnull:     true
  expr:       true
  immed:      true
  indent:     2
  latedef:    true
  newcap:     true
  noarg:      true
  sub:        true
  trailing:   true
  undef:      true
  unused:     true
  globals:
    jQuery:   true
    "$":      true
