# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &default
  secret_key_base:
  devise_secret_key:

  cloudinary:
    cloud_name:
    api_key:
    api_secret:

  google:
    # Configuration values for Google API
    api_key:
    # Configuration values for Oauth through Google
    client_id:
    client_secret:
    app_name:

  pusher:
    app_id:
    key:
    secret:

  smtp:
    address: test@test.com
    port:
    user_name:
    password:
    domain:
    send_email: false
    raise_delivery_errors: false

  psql:
    host: localhost
    username:
    password:

test:
  <<: *default

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

  cloudinary:
    cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>

  google:
    # Configuration values for Google API
    api_key: <%= ENV["GOOGLE_API_KEY"] %>
    # Configuration values for Oauth through Google
    client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
    client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
    app_name: <%= ENV["GOOGLE_APP_NAME"] %>

  pusher:
    app_id: <%= ENV["PUSHER_APP_ID"] %>
    key: <%= ENV["PUSHER_KEY"] %>
    secret: <%= ENV["PUSHER_SECRET"] %>

  smtp:
    address: <%= ENV["SMTP_ADDRESS"] %>
    port: <%= ENV["SMTP_PORT"] %>
    user_name: <%= ENV["SMTP_USER_NAME"] %>
    password: <%= ENV["SMTP_PASSWORD"] %>
    domain: <%= ENV["SMTP_DOMAIN"] %>
    send_email: <%= ENV["SEND_EMAIL"] %>
    raise_delivery_errors: <%= ENV["RAISE_DELIVERY_ERRORS"] %>

  psql:
    host: <%= ENV["PSQL_HOST"] %>
    username: <%= ENV["PSQL_USERNAME"] %>
    password: <%= ENV["PSQL_PASSWORD"] %>
