.\" generated with Ronn/v0.7.3
.\" https://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT2GV" "1" "April 2013" "" ""
.
.SH "NAME"
\fBgit2gv\fR \- show your git commits graphically
.
.SH "SYNOPSIS"
\fBgit2gv\fR [\fB\-T\fR\fIformat\fR] [\fB\-o\fR\fIfile\fR] [\fB\-h\fR] [\fB\-V\fR]
.
.SH "DESCRIPTION"
\fBgit2gv\fR is a tool that allows you to show your git commits graphically\.
.
.P
See </usr/share/doc/ruby\-graphviz/> for more details\.
.
.SH "OPTIONS"
.
.TP
\fB\-T\fR, \fB\-\-output\-format\fR [\fIformat\fR]
Output format (default: png)
.
.TP
\fB\-\-nothugly\fR
Use nothugly if SVG output
.
.TP
\fB\-o\fR, \fB\-\-output\-file\fR [\fIfile\fR]
Path to output image file (default: STDOUT)
.
.TP
\fB\-p\fR, \fB\-\-path\fR
Graphviz path
.
.TP
\fB\-V\fR, \fB\-\-version\fR
Show version
.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this usage message
.
.SH "AUTHOR"
Copyright 2004\-2013 Gregoire Lejeune
.
.P
This manual page is written by Praveen Arimbrathodiyl \fIpraveen@debian\.org\fR for Debian GNU System (GNU/Linux, GNU/kFreeBSD, GNU/Hurd)\.
