sudo: false
cache: bundler
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-9.1.5.0
  - jruby-head

before_install:
  - gem install bundler --no-document -v '~> 1.13'
before_script:
  - unset JRUBY_OPTS
