os:
  - linux
  - osx

rvm:
  - 1.9.3
  - jruby-9.1.9.0
  - rbx-3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

sudo: true # Necessary to fix JRuby

cache: bundler

before_install:
  - "echo 'gem: --no-document' > ~/.gemrc"
  - gem update --system
  - gem install bundler  # Necessary to fix 1.9.3

env:
  global:
  matrix:
    - CHILDPROCESS_POSIX_SPAWN=true CHILDPROCESS_UNSET=should-be-unset
    - CHILDPROCESS_POSIX_SPAWN=false CHILDPROCESS_UNSET=should-be-unset

matrix:
  allow_failures:
    - rvm: rbx-3
    - rvm: jruby-9.1.9.0
    - rvm: ruby-head
    - env: "CHILDPROCESS_POSIX_SPAWN=true"
  exclude:
    # Travis does not provide 1.9.3 on OSX
  - rvm: 1.9.3
    os: osx
    # Travis does not provide 2.0.0 on it latest version of OSX
  - rvm: 2.0.0
    os: osx
