before_install:
  - gem update bundler rake
before_script:
  - unset RAILS_ENV
  - unset RACK_ENV
branches:
  only:
    - master
cache: bundler
env:
  global:
    secure: | # CODECLIMATE_REPO_TOKEN
      Pm3j2/BtAzMtqRMP83rFvDtpUNeIAdLMzwH62In+3h/AE8gHDArGYS+jmChw
      2hKVjwzVUTWZlpSEocqAg/YIDB3BJzWmyc6UP+VA0gji6HsufXYTmKAVPSVY
      TQ7mPPP7hm95e3SkFbLdLbGkQfLdjIKeMY5lY/knX+QKUCjO52Y=
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails31.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 1.9.3
  - "2.0"
  - "2.1"
  - "2.2"
  - ruby-head
script: bundle exec rspec
sudo: false
